# yaml-language-server: $schema=https://raw.githubusercontent.com/mui/mui-toolpad/v0.6.0/docs/schemas/v1/definitions.json#properties/Page

apiVersion: v1
kind: page
spec:
  title: muiTeamPullRequestReviews
  display: shell
  content:
    - component: Text
      name: text
      layout:
        columnSize: 1
      props:
        value: PR reviews by team members
    - component: Chart
      name: muiPRReviewsPerTeam
      layout:
        columnSize: 1
      props:
        data:
          - label: mui/material-ui
            kind: bar
            data:
              $$jsExpression: materialUIReviewsQuery.data
            color: '#1976d2'
            xKey: t_month
            yKey: cnt
          - label: mui/base-ui
            kind: bar
            data:
              $$jsExpression: baseUIReviewsQuery.data
            color: '#4caf50'
            xKey: t_month
            yKey: cnt
          - label: mui/pigment-css
            kind: bar
            data:
              $$jsExpression: pigmentCSSReviewsQuery.data
            color: '#B800D8'
            xKey: t_month
            yKey: cnt
        sx:
          zIndex: 0
    - component: codeComponent.Diff
      name: diff
  queries:
    - name: materialUIReviewsQuery
      query:
        function: functions.ts#getTeamPullRequestReviews
        kind: local
    - name: baseUIReviewsQuery
      mode: query
      query:
        function: functions.ts#getTeamPullRequestReviews
        kind: local
      parameters:
        - name: repo
          value: mui/base-ui
    - name: pigmentCSSReviewsQuery
      mode: query
      query:
        function: functions.ts#getTeamPullRequestReviews
        kind: local
      parameters:
        - name: repo
          value: mui/pigment-css
  alias:
    - gtOs1gW
