apiVersion: v1
kind: page
spec:
  id: gtOs1gW
  title: muiTeamPullRequestReviews
  display: shell
  content:
    - component: PageRow
      name: pageRow1
      children:
        - component: Text
          name: text
          props:
            value: Material UI - team repo stats
    - component: PageRow
      name: pageRow
      children:
        - component: Chart
          name: muiPRReviewsPerTeam
          props:
            data:
              - label: Number of reviews
                kind: bar
                data:
                  $$jsExpression: |
                    query.data
                color: "#1976d2"
                xKey: t_month
                yKey: cnt
  queries:
    - name: query
      query:
        function: functions.ts#getTeamPullRequestReviews
        kind: local
